In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [5]:
data=np.random.randint(0,100,(10,2))

In [6]:
data

array([[90, 51],
       [ 7,  2],
       [87, 29],
       [84, 95],
       [32, 52],
       [93, 48],
       [ 3, 63],
       [17,  2],
       [48, 72],
       [91, 50]])

In [7]:
scaler_model=MinMaxScaler()

In [8]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [9]:
scaler_model.fit(data)

C:\Users\Patrick\.conda\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

MinMaxScaler(copy=True, feature_range=(0, 1))

But we can both fit and transform our data in one command. Lets do this

In [13]:
scaler_model.fit_transform(data)

C:\Users\Patrick\.conda\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

array([[0.96666667, 0.52688172],
       [0.04444444, 0.        ],
       [0.93333333, 0.29032258],
       [0.9       , 1.        ],
       [0.32222222, 0.53763441],
       [1.        , 0.49462366],
       [0.        , 0.65591398],
       [0.15555556, 0.        ],
       [0.5       , 0.75268817],
       [0.97777778, 0.51612903]])

We are now going to perform train_test_split on our data

In [14]:
import pandas as pd

In [15]:
myData=np.random.randint(0,101,(50,4))

In [16]:
myData

array([[ 59,  27,  26,  40],
       [ 85,  71,   1,  39],
       [ 97,  34,  80,   8],
       [ 74,  93,  69,   2],
       [ 82,  27,  36,  86],
       [ 10,  45,  76,  24],
       [ 24,  98,  23,  15],
       [ 98,  32,  17,  91],
       [ 35,  19,  80,  88],
       [  1,  81,   4,  51],
       [ 81,  78,  89,  62],
       [ 26,  67,  44,  51],
       [ 25,   3,  84,  29],
       [ 16,  64,  14,  73],
       [ 51,  88,  93,  60],
       [ 87,  94,   2,  45],
       [ 83,  49,  81,  95],
       [ 71,  22,  26,  56],
       [ 21,   5,  17,  14],
       [ 86,  84,  78,   2],
       [ 73,  69,   7,  83],
       [ 13,  12,  31,   7],
       [ 68,  57,  78,  13],
       [ 69,  48,  69,  74],
       [  2,   7,  90,  44],
       [ 82,  94,   1,  73],
       [ 92,  67,  59,  74],
       [100,   1,  57,  33],
       [ 80,  82,  76,  33],
       [ 61,  21,  59,  87],
       [ 43,  73,  90,  85],
       [ 27,   6,  12,  84],
       [  0,   8,  50,  15],
       [ 15,  38,  36,  38],
       [100,  36,  20,   8],
       [ 44,  29,  46,  13],
       [ 66,  71,  18,  78],
       [ 61,   6,   3,  14],
       [ 30,  60,  49,  36],
       [ 55,  94,  99,   6],
       [ 39,  32,  85,  54],
       [ 33,  73,  44,  45],
       [  0,   3,  53,  69],
       [ 76,  36,  33,  41],
       [ 82,  82,  12,  98],
       [ 89,  30,  38,  46],
       [ 65,  25,   0,  13],
       [ 15,  15,  75,  83],
       [ 62,   6,  97,   6],
       [ 85,  20,  29,  63]])

In [19]:
df=pd.DataFrame(data=myData)

In [20]:
df

      0   1   2   3
0    59  27  26  40
1    85  71   1  39
2    97  34  80   8
3    74  93  69   2
4    82  27  36  86
5    10  45  76  24
6    24  98  23  15
7    98  32  17  91
8    35  19  80  88
9     1  81   4  51
10   81  78  89  62
11   26  67  44  51
12   25   3  84  29
13   16  64  14  73
14   51  88  93  60
15   87  94   2  45
16   83  49  81  95
17   71  22  26  56
18   21   5  17  14
19   86  84  78   2
20   73  69   7  83
21   13  12  31   7
22   68  57  78  13
23   69  48  69  74
24    2   7  90  44
25   82  94   1  73
26   92  67  59  74
27  100   1  57  33
28   80  82  76  33
29   61  21  59  87
30   43  73  90  85
31   27   6  12  84
32    0   8  50  15
33   15  38  36  38
34  100  36  20   8
35   44  29  46  13
36   66  71  18  78
37   61   6   3  14
38   30  60  49  36
39   55  94  99   6
40   39  32  85  54
41   33  73  44  45
42    0   3  53  69
43   76  36  33  41
44   82  82  12  98
45   89  30  38  46
46   65  25   0  13
47   15  15  75  83
48   62   6  97   6
49   85  20  29  63

But we want to name our columns

In [21]:
df=pd.DataFrame(data=myData,columns=['f1','f2','f3','label'])

In [22]:
df

     f1  f2  f3  label
0    59  27  26     40
1    85  71   1     39
2    97  34  80      8
3    74  93  69      2
4    82  27  36     86
5    10  45  76     24
6    24  98  23     15
7    98  32  17     91
8    35  19  80     88
9     1  81   4     51
10   81  78  89     62
11   26  67  44     51
12   25   3  84     29
13   16  64  14     73
14   51  88  93     60
15   87  94   2     45
16   83  49  81     95
17   71  22  26     56
18   21   5  17     14
19   86  84  78      2
20   73  69   7     83
21   13  12  31      7
22   68  57  78     13
23   69  48  69     74
24    2   7  90     44
25   82  94   1     73
26   92  67  59     74
27  100   1  57     33
28   80  82  76     33
29   61  21  59     87
30   43  73  90     85
31   27   6  12     84
32    0   8  50     15
33   15  38  36     38
34  100  36  20      8
35   44  29  46     13
36   66  71  18     78
37   61   6   3     14
38   30  60  49     36
39   55  94  99      6
40   39  32  85     54
41   33  73  44     45
42    0   3  53     69
43   76  36  33     41
44   82  82  12     98
45   89  30  38     46
46   65  25   0     13
47   15  15  75     83
48   62   6  97      6
49   85  20  29     63

Lets imagin this is our entire dataset and we want to split it into training set and testing set

In [34]:
X=df[['f1','f2','f3']]
#where x is our features

In [35]:
X

     f1  f2  f3
0    59  27  26
1    85  71   1
2    97  34  80
3    74  93  69
4    82  27  36
5    10  45  76
6    24  98  23
7    98  32  17
8    35  19  80
9     1  81   4
10   81  78  89
11   26  67  44
12   25   3  84
13   16  64  14
14   51  88  93
15   87  94   2
16   83  49  81
17   71  22  26
18   21   5  17
19   86  84  78
20   73  69   7
21   13  12  31
22   68  57  78
23   69  48  69
24    2   7  90
25   82  94   1
26   92  67  59
27  100   1  57
28   80  82  76
29   61  21  59
30   43  73  90
31   27   6  12
32    0   8  50
33   15  38  36
34  100  36  20
35   44  29  46
36   66  71  18
37   61   6   3
38   30  60  49
39   55  94  99
40   39  32  85
41   33  73  44
42    0   3  53
43   76  36  33
44   82  82  12
45   89  30  38
46   65  25   0
47   15  15  75
48   62   6  97
49   85  20  29

In [36]:
y=df['label']
#so this is the lable we are trying to predict

In [37]:
y

0     40
1     39
2      8
3      2
4     86
5     24
6     15
7     91
8     88
9     51
10    62
11    51
12    29
13    73
14    60
15    45
16    95
17    56
18    14
19     2
20    83
21     7
22    13
23    74
24    44
25    73
26    74
27    33
28    33
29    87
30    85
31    84
32    15
33    38
34     8
35    13
36    78
37    14
38    36
39     6
40    54
41    45
42    69
43    41
44    98
45    46
46    13
47    83
48     6
49    63
Name: label, dtype: int32

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [40]:
X_train.shape

(33, 3)

In [41]:
X_test.shape

(17, 3)